# Generated by Django 4.1.4 on 2023-01-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('info_contact', models.CharField(max_length=200)),
                ('theme', models.CharField(max_length=150)),
                ('categorie', models.CharField(max_length=200)),
                ('modaliter', models.TextField(default=False)),
                ('dat', models.DateTimeField(auto_now_add=True)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='uploads/images')),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
