# Generated by Django 4.1.4 on 2023-01-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonce',
            old_name='titre',
            new_name='annonceur',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='modaliter',
            field=models.CharField(max_length=200),
        ),
    ]
